### PR TITLE
fix(ClientRequest): prevent `req.write()` callbacks from being called twice on passthrough

### LINKED ISSUE #684: ClientRequest: write callback get called twice (`FormData` are broken)
The regression is introduced in `0.36.10`. When the interceptor is applied, we call the write callback twice.
```js
const https = require('https');
const { ClientRequestInterceptor } = require('@mswjs/interceptors/ClientRequest')

const int = new ClientRequestInterceptor()
int.apply()

const req = https.request('https://webhook.site/ae950c30-b7bf-46e7-bb40-2c32ca132689', {
  method: 'POST',
},
  res => {
    console.log(res.statusCode);
    res.resume();
  })


req.write('mamma mia', null, () => {
  console.log(1); // prints 1 twice
  req.end()
})
```

----

From what I see, for some reason, Node calls to the callback as well in https://github.com/nodejs/node/blob/3fb2ea8689250a3d39d9c66afd7301c7caa644c2/lib/internal/streams/writable.js#L764

I'm not sure why tho.

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #684 
- Related to #674 
- Related to https://github.com/mswjs/msw/issues/2326

## Changes

During the `flushWriteBuffer()`, set the invoked callback on the write args to `undefined` so it doesn't get called again (twice) during passthrough of requests that call `request.end()` within the `request.write()` callback. The issue is only reproducible in that scenario and doesn't happen on sequential write/end calls.

### CODE REVIEW

File: src/interceptors/ClientRequest/MockHttpSocket.ts [hunk 1]
```diff
@@ -420,13 +420,17 @@ export class MockHttpSocket extends MockSocket {
...
+    for (const writeCall of this.writeBuffer) {
+      if (typeof writeCall[2] === 'function') {
+        writeCall[2]()
+        /**
+         * @note Remove the callback from the write call
+         * so it doesn't get called twice on passthrough
+         * if `request.end()` was called within `request.write()`.
+         * @see https://github.com/mswjs/interceptors/issues/684
+         */
+        writeCall[2] = undefined
```
Comment (kettanaito) [inline src/interceptors/ClientRequest/MockHttpSocket.ts:432]: I decided to go with the replacement approach because it's simpler than introducing an internal symbol.

**Comment by mikicho** [comment]
Thanks! `nock` tests pass. 🎉 

> so it doesn't get called again (twice) during passthrough

I forgot that `interceptors` passthrough the request by default 🤦

File: src/interceptors/ClientRequest/MockHttpSocket.ts (hunk 1 above)
Comment (mikicho) [reply src/interceptors/ClientRequest/MockHttpSocket.ts:432]: I agree.

**Review by mikicho — APPROVED** [review]

**Comment by kettanaito** [comment]
Thanks for looking at this one! 🎉

**Comment by kettanaito** [comment]
## Released: v0.37.2 🎉

This has been released in v0.37.2!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.37.2)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.37.2)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
