### PR TITLE
fix(ClientRequest): prevent `rawHeaders` from being shared across instances

### LINKED ISSUE #681: Cloned `Headers` modifies future clones
Hi,

When updating MSW to the latest version we started to get leakage between cloned `Headers` objects.

Here is a reproduction:
```js
const original = new Headers();

const clone1 = new Headers(original);

clone1.set('Content-Type', 'application/json')

const clone2 = new Headers(original);

console.log('Original', original.get('Content-Type'));
console.log('Clone1', clone1.get('Content-Type'));
console.log('Clone2', clone2.get('Content-Type'));
```

When running in MSW context, this is the output:
```
Original null
Clone1 application/json
Clone2 application/json
```
The `clone2` is expected to be `null` here, the `application/json` is only applied to `clone1` and never the `original`.

When running in a pure node context without MSW we get expected behavior:
```
Original null
Clone1 application/json
Clone2 null
```

### PR DESCRIPTION
**Pull request by mikicho**
fixes #681

### CODE REVIEW

File: src/interceptors/ClientRequest/utils/recordRawHeaders.ts [hunk 1]
```diff
@@ -118,7 +118,7 @@ export function recordRawFetchHeaders() {
             [Reflect.get(headersInit, kRawHeaders)],
             newTarget
           )
-          ensureRawHeadersSymbol(headers, Reflect.get(headersInit, kRawHeaders))
+          ensureRawHeadersSymbol(headers, [...Reflect.get(headersInit, kRawHeaders)])
```
Comment (kettanaito) [inline src/interceptors/ClientRequest/utils/recordRawHeaders.ts:121]: It would be great to add a `@note` comment here explaining that spreading the headers creates their copy + what issue this prevents.

File: src/interceptors/ClientRequest/utils/recordRawHeaders.test.ts [hunk 2]
```diff
@@ -241,3 +241,15 @@ it('does not throw on using Headers before recording', () => {
   request.headers.set('X-My-Header', '1')
   expect(getRawFetchHeaders(request.headers)).toEqual([['X-My-Header', '1']])
 })
+
+it('does not use the same instance of rawHeaders', async () => {
```
Comment (kettanaito) [inline src/interceptors/ClientRequest/utils/recordRawHeaders.test.ts:245]: `rawHeaders` inclusion in the name is probably not needed. How about

```ts
it('isolates the headers on the instance basis')
```

Comment (kettanaito) [reply src/interceptors/ClientRequest/utils/recordRawHeaders.test.ts:245]: I also like linking GitHub issues above the test case names so it's easier to grasp the context for bug fixes.

**Review by kettanaito — APPROVED** [review]

**Comment by kettanaito** [comment]
## Released: v0.37.4 🎉

This has been released in v0.37.4!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.37.4)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.37.4)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
