### PR TITLE
fix(IsomorphicRequest): add "credentials" property

### LINKED ISSUE #18: Handle request "credentials" for browser-like environments
## GitHub

- Related to https://github.com/mswjs/msw/issues/189

### PR DESCRIPTION
**Pull request by kettanaito**
## GitHub

- Closes #18 
- Fixes https://github.com/mswjs/msw/issues/967

## Changes

- Adds a new "credentials" property on the `IsomorphicRequest` object.
- XMLHttpRequest: Coerces `this.withCredentials` option to "include" (`true`) or "omit" (`false`).
- ClientRequest: Always sets `request.credentials` to "omit" (no way to specify the behavior).
- Improves in-browser request utilities for `fetch` and `XMLHttpRequest`. **Removes direct assertions from the `*.runtime.js` files.** Moves assertions to the test's context. 

## Roadmap

- [x] Add integration tests.
- [x] Update the README to list the newly added "credentials" property on the `IsomorphicRequest`. Explain its values.

### CODE REVIEW

File: src/createInterceptor.ts [hunk 1]
```diff
@@ -19,6 +19,7 @@ export interface IsomorphicRequest {
   url: URL
   method: string
   headers: Headers
+  credentials: 'omit' | 'include' | 'same-origin'
```
Comment (kettanaito) [inline src/createInterceptor.ts:22]: I'm preserving the "same-origin" option because the `fetch` interceptor is designed for the browser where such an option is legitimate and possible. It's a no-op in Node.js.

File: src/interceptors/ClientRequest/NodeClientRequest.ts [hunk 2]
```diff
@@ -292,6 +292,7 @@ export class NodeClientRequest extends ClientRequest {
       id: uuidv4(),
       url: this.url,
       method: this.options.method || 'GET',
+      credentials: 'omit',
```
Comment (kettanaito) [inline src/interceptors/ClientRequest/NodeClientRequest.ts:295]: No way to control the credentials behavior in `ClientRequest`.

**Comment by kettanaito** [comment]
"credentials" is generally a concern of `window.fetch` and any browser-like environments that polyfill it (via `XMLHttpRequest`). This change primarily affects those two interceptors.

File: src/createInterceptor.ts [hunk 3]
```diff
@@ -21,6 +21,11 @@ export interface IsomorphicRequest {
   url: URL
   method: string
   headers: Headers
+  /**
+   * The value of the request client's "credentials" option
+   * or a compatible alternative (i.e. `withCredentials` for `XMLHttpRequest`).
+   * Always equals to "omit" in Node.js.
+   */
   credentials: RequestCredentials
```
Comment (kettanaito) [inline src/createInterceptor.ts:29]: We do not document `IsomorphicRequest` in README. I'm adding this short description directly on the property.

**Comment by crutch12** [comment]
Are you going to release it?

**Comment by kettanaito** [comment]
@crutch12, yes, we will. You can use local resolution for `0.13.0` for now, there are no breaking changes between 0.12 and 0.13.
