### PR TITLE
fix(xhr): handle responses without body correctly

### LINKED ISSUE #379: `XMLHttpRequest` failing to construct `Response` when body status is `null`
Screenshot 2023-05-25 at 12 00 56 PM

Screenshot 2023-05-25 at 12 05 54 PM

Screenshot 2023-05-25 at 12 13 10 PM

When using the `XMLHttpRequestInterceptor` these errors are thrown, crashing the webpage. 

It does not appear when using other interceptors.

This is the code I am using - 

```
import { BatchInterceptor } from '@mswjs/interceptors'
import { FetchInterceptor } from '@mswjs/interceptors/fetch'
import { XMLHttpRequestInterceptor } from '@mswjs/interceptors/XMLHttpRequest'


const interceptor = new BatchInterceptor({
    name: 'my-interceptor',
    interceptors: [new FetchInterceptor(), new XMLHttpRequestInterceptor()],
})

interceptor.apply()

interceptor.on('request', async (e: any, request: any) => {
    console.log("request", await e.clone().json())
})

interceptor.on('response', async (res: any, request: any) => {
    console.log("response", await res.clone().json())
})
```

### PR DESCRIPTION
**Pull request by avivasyuta**
- Fixes #379

### CODE REVIEW

File: src/interceptors/XMLHttpRequest/utils/createResponse.ts [hunk 1]
```diff
@@ -6,7 +8,19 @@ export function createResponse(
...
-  return new Response(body, {
+  /**
+   * Handle XMLHttpRequest responses that must have null as the
+   * response body when represented using Fetch API Response.
+   * XMLHttpRequest response will always have an empty string
+   * as the "request.response" in those cases, resulting in an error
+   * when constructing a Response instance.
+   * @see https://github.com/mswjs/interceptors/issues/379
+   */
+  const responseBodyOrNull = statusCodesWithoutBody.includes(request.status)
```
Comment (kettanaito) [inline src/interceptors/XMLHttpRequest/utils/createResponse.ts:19]: I moved this check to the `createResponse()` function so it always produces the correct response no matter what XHR instance it's given. This logic belongs here.

File: test/modules/XMLHttpRequest/response/xhr-response-without-body.test.ts [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+afterEach(() => {
+  vi.resetAllMocks()
+})
+
+afterAll(async () => {
+  interceptor.dispose()
+  await httpServer.close()
+})
+
+it('represents a 204 response without body using fetch api response', async () => {
```
Comment (kettanaito) [inline test/modules/XMLHttpRequest/response/xhr-response-without-body.test.ts:34]: Take a look, I've expanded the tests, creating three separate test cases instead of iterating over the list of status codes. It's crucial to keep the tests as flat and straightforward as possible. This means as little logic specific to tests as possible, like `test.each()`. This results in tests that are easy to find, read, change, and remove.

File: test/modules/XMLHttpRequest/response/xhr-response-without-body.test.ts [hunk 3]
```diff
@@ -0,0 +1,108 @@
+// @vitest-environment jsdom
+import { afterAll, afterEach, beforeAll, expect, it, vi } from 'vitest'
+import { HttpServer } from '@open-draft/test-server/http'
+import { XMLHttpRequestInterceptor } from '../../../../src/interceptors/XMLHttpRequest'
+import { createXMLHttpRequest, useCors } from '../../../helpers'
+import type { HttpRequestEventMap } from '../../../../src'
+
+const httpServer = new HttpServer((app) => {
+  app.use(useCors)
+  app.get('/:statusCode', (req, res) =>
```
Comment (kettanaito) [inline test/modules/XMLHttpRequest/response/xhr-response-without-body.test.ts:10]: I made this server route return whichever response status code that was requested by the client.

File: src/interceptors/XMLHttpRequest/utils/createResponse.ts (hunk 1 above)
Comment (kettanaito) [reply src/interceptors/XMLHttpRequest/utils/createResponse.ts:19]: @avivasyuta, also note that representing the status codes that must not have a body in an array is more practical in this case than an object. At its core, we want a list of things, so an array is the right choice here!

**Review by kettanaito — APPROVED** [review]
The changes look great! 👏 I've only moved the things around. Fantastic work done, @avivasyuta.

File: src/interceptors/XMLHttpRequest/utils/createResponse.ts (hunk 1 above)
Comment (avivasyuta) [reply src/interceptors/XMLHttpRequest/utils/createResponse.ts:19]: Yes, at first I thought that it would be more productive to use an object, but for three elements this can be neglected.

File: test/modules/XMLHttpRequest/response/xhr-response-without-body.test.ts (hunk 3 above)
Comment (avivasyuta) [reply test/modules/XMLHttpRequest/response/xhr-response-without-body.test.ts:10]: This is a great approach. I didn't think of it right away.

**Comment by kettanaito** [comment]
Yet another amazing contribution nailed. Let's ship this 🚀

File: test/modules/XMLHttpRequest/response/xhr-response-without-body.test.ts (hunk 3 above)
Comment (kettanaito) [reply test/modules/XMLHttpRequest/response/xhr-response-without-body.test.ts:10]: I liked how you orchestrated the test! This is but a small adjustment.

**Comment by kettanaito** [comment]
## Released: v0.24.1 🎉

This has been released in v0.24.1!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.24.1)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.24.1)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
