### PR TITLE
fix(ClientRequest): support the "auth" option

### LINKED ISSUE #438: Support username:password in NodeClientRequest
The request fails when we send `auth` option to `http.request`:

```js
http.request({
  hostname: 'example.test',
  auth: 'username:password',
  path: '/',
})
```

logs
```
20:33:47:990 [http:request GET http://username:password@example.test/] constructing ClientRequest using options: {"url":"http://username:password@example.test/","requestOptions":{"hostname":"example.test","auth":"username:password","path":"/","protocol":"http:","method":"GET","agent":{"_events":{},"_eventsCount":2,"defaultPort":80,"protocol":"http:","options":{"noDelay":true,"path":null},"requests":{},"sockets":{"example.test:80:":[{"connecting":true,"_hadError":false,"_parent":null,"_host":"example.test","_closeAfterHandlingError":false,"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":[],"flowing":null,"ended":false,"endEmitted":false,"reading":false,"constructed":true,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":false,"autoDestroy":true,"destroyed":false,"errored":null,"closed":false,"closeEmitted":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"dataEmitted":false,"decoder":null,"encoding":null},"_events":{},"_eventsCount":6,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":false,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"afterWriteTickInfo":null,"buffered":[],"bufferedIndex":0,"allBuffers":true,"allNoop":true,"pendingcb":0,"constructed":true,"prefinished":false,"errorEmitted":false,"emitClose":false,"autoDestroy":true,"errored":null,"closed":false,"closeEmitted":false},"allowHalfOpen":false,"_sockname":null,"_pendingData":null,"_pendingEncoding":"","server":null,"_server":null}]},"freeSockets":{},"keepAliveMsecs":1000,"keepAlive":false,"maxSockets":null,"maxFreeSockets":256,"scheduling":"lifo","maxTotalSockets":null,"totalSocketCount":1},"_defaultAgent":{"_events":{},"_eventsCount":2,"defaultPort":80,"protocol":"http:","options":{"keepAlive":true,"scheduling":"lifo","timeout":5000,"noDelay":true,"path":null},"requests":{},"sockets":{},"freeSockets":{},"keepAliveMsecs":1000,"keepAlive":true,"maxSockets":null,"maxFreeSockets":256,"scheduling":"lifo","maxTotalSockets":null,"totalSocketCount":0}}}
```

I think we should add some logic into the `createRequest` function
https://github.com/mswjs/interceptors/blob/main/src/interceptors/ClientRequest/NodeClientRequest.ts#L141

I think I can open a PR if you think I'm correct and we should fix the `createRequest` function

### PR DESCRIPTION
**Pull request by mikicho**
Options: https://nodejs.org/api/http.html#httprequesturl-options-callback

@kettanaito 
* Not sure if this is where the test should be
* Also, I'm not sure if this is what you mean by "Do not propagate username and password onto the [NodeClientRequest.url](https://github.com/mswjs/interceptors/blob/b8bce893d7e9642a9836ad29a0903562dde7fbca/src/interceptors/ClientRequest/NodeClientRequest.ts#L71)", I just override the username/password. Please let me know if you have something else in mind.

closes #438

### CODE REVIEW

File: src/interceptors/ClientRequest/utils/createRequest.ts [hunk 1]
```diff
@@ -20,6 +20,21 @@ export function createRequest(clientRequest: NodeClientRequest): Request {
     }
   }
 
+  /**
+   * Translate the authentication from the request URL to
+   * the request "Authorization" header.
+   * @see https://github.com/mswjs/interceptors/issues/438
+   */
+  if (clientRequest.url.username && clientRequest.url.password) {
```
Comment (kettanaito) [inline src/interceptors/ClientRequest/utils/createRequest.ts:28]: I've moved this logic to the `createRequest` function itself since it should always translate `ClientRequest` to a valid `Request` instance.

File: src/utils/getUrlByRequestOptions.ts [hunk 2]
```diff
@@ -159,7 +166,10 @@ export function getUrlByRequestOptions(options: ResolvedRequestOptions): URL {
     : ''
   logger.info('auth string:', authString)
 
-  const url = new URL(`${protocol}//${authString}${hostname}${path}`)
+  const url = new URL(`${protocol}//${hostname}${path}`)
+  url.username = credentials?.username || ''
```
Comment (kettanaito) [inline src/utils/getUrlByRequestOptions.ts:170]: TIL you can set `username` and `password` on the existing URL instance since `href` is a getter. This makes the URL construct a bit more readable.

File: test/modules/http/intercept/http.request.test.ts [hunk 3]
```diff
@@ -229,3 +229,49 @@ it('intercepts an http.request given RequestOptions without a protocol', async (
...
+  expect(request.credentials).toBe('same-origin')
+  expect(request.body).toBe(null)
+})
+
+it('intercepts an http.request with a URL with "username" and "password"', async () => {
+  const username = 'john'
+  const password = 'secret123'
+  const req = http.request(
+    // The request URL can include the basic auth directly.
+    new URL(
```
Comment (kettanaito) [inline test/modules/http/intercept/http.request.test.ts:259]: I've also added a test case for when the auth is included in the `URL` itself.

**Review by kettanaito — APPROVED** [review]
I did a few minor adjustments but it looks great! Thank you for opening this, @mikicho 👏

**Comment by kettanaito** [comment]
Please let me know if this sufficiently addresses the use case. If it does, we can proceed with releasing this.

**Comment by kettanaito** [comment]
## Released: v0.25.4 🎉

This has been released in v0.25.4!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.25.4)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.25.4)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
